//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdorseToEDM.EmailProviderWcfSvc {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MailParams", Namespace="http://schemas.datacontract.org/2004/07/EmailManagement.DataContract.StructureMod" +
        "el")]
    [System.SerializableAttribute()]
    public partial class MailParams : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BodyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EdorseToEDM.EmailProviderWcfSvc.File_Upload[] FileAttechmentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsBigMailBodyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsHtmlBodyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsKeepMailLogField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long MailIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EdorseToEDM.EmailProviderWcfSvc.MailReceipients ReceipientsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EdorseToEDM.EmailProviderWcfSvc.MailTrackingReferenceOptional ReferenceOptionalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubjectField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Body {
            get {
                return this.BodyField;
            }
            set {
                if ((object.ReferenceEquals(this.BodyField, value) != true)) {
                    this.BodyField = value;
                    this.RaisePropertyChanged("Body");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EdorseToEDM.EmailProviderWcfSvc.File_Upload[] FileAttechments {
            get {
                return this.FileAttechmentsField;
            }
            set {
                if ((object.ReferenceEquals(this.FileAttechmentsField, value) != true)) {
                    this.FileAttechmentsField = value;
                    this.RaisePropertyChanged("FileAttechments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string From {
            get {
                return this.FromField;
            }
            set {
                if ((object.ReferenceEquals(this.FromField, value) != true)) {
                    this.FromField = value;
                    this.RaisePropertyChanged("From");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsBigMailBody {
            get {
                return this.IsBigMailBodyField;
            }
            set {
                if ((this.IsBigMailBodyField.Equals(value) != true)) {
                    this.IsBigMailBodyField = value;
                    this.RaisePropertyChanged("IsBigMailBody");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsHtmlBody {
            get {
                return this.IsHtmlBodyField;
            }
            set {
                if ((this.IsHtmlBodyField.Equals(value) != true)) {
                    this.IsHtmlBodyField = value;
                    this.RaisePropertyChanged("IsHtmlBody");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsKeepMailLog {
            get {
                return this.IsKeepMailLogField;
            }
            set {
                if ((this.IsKeepMailLogField.Equals(value) != true)) {
                    this.IsKeepMailLogField = value;
                    this.RaisePropertyChanged("IsKeepMailLog");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long MailId {
            get {
                return this.MailIdField;
            }
            set {
                if ((this.MailIdField.Equals(value) != true)) {
                    this.MailIdField = value;
                    this.RaisePropertyChanged("MailId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EdorseToEDM.EmailProviderWcfSvc.MailReceipients Receipients {
            get {
                return this.ReceipientsField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceipientsField, value) != true)) {
                    this.ReceipientsField = value;
                    this.RaisePropertyChanged("Receipients");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EdorseToEDM.EmailProviderWcfSvc.MailTrackingReferenceOptional ReferenceOptional {
            get {
                return this.ReferenceOptionalField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferenceOptionalField, value) != true)) {
                    this.ReferenceOptionalField = value;
                    this.RaisePropertyChanged("ReferenceOptional");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Subject {
            get {
                return this.SubjectField;
            }
            set {
                if ((object.ReferenceEquals(this.SubjectField, value) != true)) {
                    this.SubjectField = value;
                    this.RaisePropertyChanged("Subject");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MailReceipients", Namespace="http://schemas.datacontract.org/2004/07/EmailManagement.DataContract")]
    [System.SerializableAttribute()]
    public partial class MailReceipients : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] BCCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] CCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] ToField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] BCC {
            get {
                return this.BCCField;
            }
            set {
                if ((object.ReferenceEquals(this.BCCField, value) != true)) {
                    this.BCCField = value;
                    this.RaisePropertyChanged("BCC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] CC {
            get {
                return this.CCField;
            }
            set {
                if ((object.ReferenceEquals(this.CCField, value) != true)) {
                    this.CCField = value;
                    this.RaisePropertyChanged("CC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] To {
            get {
                return this.ToField;
            }
            set {
                if ((object.ReferenceEquals(this.ToField, value) != true)) {
                    this.ToField = value;
                    this.RaisePropertyChanged("To");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MailTrackingReferenceOptional", Namespace="http://schemas.datacontract.org/2004/07/EmailManagement.DataContract.StructureMod" +
        "el")]
    [System.SerializableAttribute()]
    public partial class MailTrackingReferenceOptional : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EdorseToEDM.EmailProviderWcfSvc.MailCustomeTracking[] CustomeTrackingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EdorseToEDM.EmailProviderWcfSvc.MailBaseTracking[] TrackingField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EdorseToEDM.EmailProviderWcfSvc.MailCustomeTracking[] CustomeTracking {
            get {
                return this.CustomeTrackingField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomeTrackingField, value) != true)) {
                    this.CustomeTrackingField = value;
                    this.RaisePropertyChanged("CustomeTracking");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EdorseToEDM.EmailProviderWcfSvc.MailBaseTracking[] Tracking {
            get {
                return this.TrackingField;
            }
            set {
                if ((object.ReferenceEquals(this.TrackingField, value) != true)) {
                    this.TrackingField = value;
                    this.RaisePropertyChanged("Tracking");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="File_Upload", Namespace="http://schemas.datacontract.org/2004/07/EmailManagement.DataContract")]
    [System.SerializableAttribute()]
    public partial class File_Upload : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContentType {
            get {
                return this.ContentTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentTypeField, value) != true)) {
                    this.ContentTypeField = value;
                    this.RaisePropertyChanged("ContentType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                    this.FileNameField = value;
                    this.RaisePropertyChanged("FileName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MailCustomeTracking", Namespace="http://schemas.datacontract.org/2004/07/EmailManagement.DataContract.StructureMod" +
        "el")]
    [System.SerializableAttribute()]
    public partial class MailCustomeTracking : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataType {
            get {
                return this.DataTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.DataTypeField, value) != true)) {
                    this.DataTypeField = value;
                    this.RaisePropertyChanged("DataType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KeyName {
            get {
                return this.KeyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyNameField, value) != true)) {
                    this.KeyNameField = value;
                    this.RaisePropertyChanged("KeyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KeyValue {
            get {
                return this.KeyValueField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyValueField, value) != true)) {
                    this.KeyValueField = value;
                    this.RaisePropertyChanged("KeyValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MailBaseTracking", Namespace="http://schemas.datacontract.org/2004/07/EmailManagement.DataContract.StructureMod" +
        "el")]
    [System.SerializableAttribute()]
    public partial class MailBaseTracking : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EdorseToEDM.EmailProviderWcfSvc.JobInfo[] JobsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PolicyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PolicyHoldingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> PolicyIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EdorseToEDM.EmailProviderWcfSvc.JobInfo[] Jobs {
            get {
                return this.JobsField;
            }
            set {
                if ((object.ReferenceEquals(this.JobsField, value) != true)) {
                    this.JobsField = value;
                    this.RaisePropertyChanged("Jobs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Policy {
            get {
                return this.PolicyField;
            }
            set {
                if ((object.ReferenceEquals(this.PolicyField, value) != true)) {
                    this.PolicyField = value;
                    this.RaisePropertyChanged("Policy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PolicyHolding {
            get {
                return this.PolicyHoldingField;
            }
            set {
                if ((object.ReferenceEquals(this.PolicyHoldingField, value) != true)) {
                    this.PolicyHoldingField = value;
                    this.RaisePropertyChanged("PolicyHolding");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> PolicyId {
            get {
                return this.PolicyIdField;
            }
            set {
                if ((this.PolicyIdField.Equals(value) != true)) {
                    this.PolicyIdField = value;
                    this.RaisePropertyChanged("PolicyId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JobInfo", Namespace="http://schemas.datacontract.org/2004/07/EmailManagement.DataContract.StructureMod" +
        "el")]
    [System.SerializableAttribute()]
    public partial class JobInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JobField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] SubJobsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Job {
            get {
                return this.JobField;
            }
            set {
                if ((object.ReferenceEquals(this.JobField, value) != true)) {
                    this.JobField = value;
                    this.RaisePropertyChanged("Job");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] SubJobs {
            get {
                return this.SubJobsField;
            }
            set {
                if ((object.ReferenceEquals(this.SubJobsField, value) != true)) {
                    this.SubJobsField = value;
                    this.RaisePropertyChanged("SubJobs");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MailParamsOld", Namespace="http://schemas.datacontract.org/2004/07/EmailManagement.DataContract.StructureMod" +
        "el")]
    [System.SerializableAttribute()]
    public partial class MailParamsOld : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EdorseToEDM.EmailProviderWcfSvc.MailParams BaseParamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EdorseToEDM.EmailProviderWcfSvc.ImageDataFile[] ImageDataFileInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsEmbedImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EdorseToEDM.EmailProviderWcfSvc.MailEncoding MailEncodingField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EdorseToEDM.EmailProviderWcfSvc.MailParams BaseParam {
            get {
                return this.BaseParamField;
            }
            set {
                if ((object.ReferenceEquals(this.BaseParamField, value) != true)) {
                    this.BaseParamField = value;
                    this.RaisePropertyChanged("BaseParam");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EdorseToEDM.EmailProviderWcfSvc.ImageDataFile[] ImageDataFileInfo {
            get {
                return this.ImageDataFileInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageDataFileInfoField, value) != true)) {
                    this.ImageDataFileInfoField = value;
                    this.RaisePropertyChanged("ImageDataFileInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsEmbedImage {
            get {
                return this.IsEmbedImageField;
            }
            set {
                if ((this.IsEmbedImageField.Equals(value) != true)) {
                    this.IsEmbedImageField = value;
                    this.RaisePropertyChanged("IsEmbedImage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EdorseToEDM.EmailProviderWcfSvc.MailEncoding MailEncoding {
            get {
                return this.MailEncodingField;
            }
            set {
                if ((this.MailEncodingField.Equals(value) != true)) {
                    this.MailEncodingField = value;
                    this.RaisePropertyChanged("MailEncoding");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ImageDataFile", Namespace="http://schemas.datacontract.org/2004/07/EmailManagement.DataContract.StructureMod" +
        "el")]
    [System.SerializableAttribute()]
    public partial class ImageDataFile : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ImageBytesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageKeyNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContentType {
            get {
                return this.ContentTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentTypeField, value) != true)) {
                    this.ContentTypeField = value;
                    this.RaisePropertyChanged("ContentType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] ImageBytes {
            get {
                return this.ImageBytesField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageBytesField, value) != true)) {
                    this.ImageBytesField = value;
                    this.RaisePropertyChanged("ImageBytes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageKeyName {
            get {
                return this.ImageKeyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageKeyNameField, value) != true)) {
                    this.ImageKeyNameField = value;
                    this.RaisePropertyChanged("ImageKeyName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MailEncoding", Namespace="http://schemas.datacontract.org/2004/07/EmailManagement.DataContract.StructureMod" +
        "el.Enum")]
    public enum MailEncoding : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Window874 = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UTF8 = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MailInfo", Namespace="http://schemas.datacontract.org/2004/07/EmailManagement.DataContract.StructureMod" +
        "el")]
    [System.SerializableAttribute()]
    public partial class MailInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BodyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EdorseToEDM.EmailProviderWcfSvc.File_Upload[] FileAttechmentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsBigMailBodyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsHtmlBodyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsKeepMailLogField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long MailIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EdorseToEDM.EmailProviderWcfSvc.MailReceipients ReceipientsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EdorseToEDM.EmailProviderWcfSvc.MailTrackingReferenceOptional ReferenceOptionalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime SendDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SendStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubjectField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Body {
            get {
                return this.BodyField;
            }
            set {
                if ((object.ReferenceEquals(this.BodyField, value) != true)) {
                    this.BodyField = value;
                    this.RaisePropertyChanged("Body");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EdorseToEDM.EmailProviderWcfSvc.File_Upload[] FileAttechments {
            get {
                return this.FileAttechmentsField;
            }
            set {
                if ((object.ReferenceEquals(this.FileAttechmentsField, value) != true)) {
                    this.FileAttechmentsField = value;
                    this.RaisePropertyChanged("FileAttechments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string From {
            get {
                return this.FromField;
            }
            set {
                if ((object.ReferenceEquals(this.FromField, value) != true)) {
                    this.FromField = value;
                    this.RaisePropertyChanged("From");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsBigMailBody {
            get {
                return this.IsBigMailBodyField;
            }
            set {
                if ((this.IsBigMailBodyField.Equals(value) != true)) {
                    this.IsBigMailBodyField = value;
                    this.RaisePropertyChanged("IsBigMailBody");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsHtmlBody {
            get {
                return this.IsHtmlBodyField;
            }
            set {
                if ((this.IsHtmlBodyField.Equals(value) != true)) {
                    this.IsHtmlBodyField = value;
                    this.RaisePropertyChanged("IsHtmlBody");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsKeepMailLog {
            get {
                return this.IsKeepMailLogField;
            }
            set {
                if ((this.IsKeepMailLogField.Equals(value) != true)) {
                    this.IsKeepMailLogField = value;
                    this.RaisePropertyChanged("IsKeepMailLog");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long MailId {
            get {
                return this.MailIdField;
            }
            set {
                if ((this.MailIdField.Equals(value) != true)) {
                    this.MailIdField = value;
                    this.RaisePropertyChanged("MailId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EdorseToEDM.EmailProviderWcfSvc.MailReceipients Receipients {
            get {
                return this.ReceipientsField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceipientsField, value) != true)) {
                    this.ReceipientsField = value;
                    this.RaisePropertyChanged("Receipients");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EdorseToEDM.EmailProviderWcfSvc.MailTrackingReferenceOptional ReferenceOptional {
            get {
                return this.ReferenceOptionalField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferenceOptionalField, value) != true)) {
                    this.ReferenceOptionalField = value;
                    this.RaisePropertyChanged("ReferenceOptional");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SendDate {
            get {
                return this.SendDateField;
            }
            set {
                if ((this.SendDateField.Equals(value) != true)) {
                    this.SendDateField = value;
                    this.RaisePropertyChanged("SendDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SendStatus {
            get {
                return this.SendStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.SendStatusField, value) != true)) {
                    this.SendStatusField = value;
                    this.RaisePropertyChanged("SendStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Subject {
            get {
                return this.SubjectField;
            }
            set {
                if ((object.ReferenceEquals(this.SubjectField, value) != true)) {
                    this.SubjectField = value;
                    this.RaisePropertyChanged("Subject");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EmailProviderWcfSvc.IEmailProvider")]
    public interface IEmailProvider {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmailProvider/SendMail", ReplyAction="http://tempuri.org/IEmailProvider/SendMailResponse")]
        ITUtility.ProcessResult SendMail(EdorseToEDM.EmailProviderWcfSvc.MailParams param, string userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmailProvider/SendMailByAlternateView", ReplyAction="http://tempuri.org/IEmailProvider/SendMailByAlternateViewResponse")]
        ITUtility.ProcessResult SendMailByAlternateView(out long mailId, EdorseToEDM.EmailProviderWcfSvc.MailParamsOld param, string userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmailProvider/SendMailOldVersion", ReplyAction="http://tempuri.org/IEmailProvider/SendMailOldVersionResponse")]
        ITUtility.ProcessResult SendMailOldVersion(EdorseToEDM.EmailProviderWcfSvc.MailParamsOld param, string userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmailProvider/GetMailAboutPolicyInfoByMailId", ReplyAction="http://tempuri.org/IEmailProvider/GetMailAboutPolicyInfoByMailIdResponse")]
        ITUtility.ProcessResult GetMailAboutPolicyInfoByMailId(out EdorseToEDM.EmailProviderWcfSvc.MailInfo[] mailObjects, long[] mailId, bool includeAttachment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmailProvider/GetMailAbountPolicyInfoByPolicyAndHolding", ReplyAction="http://tempuri.org/IEmailProvider/GetMailAbountPolicyInfoByPolicyAndHoldingRespon" +
            "se")]
        ITUtility.ProcessResult GetMailAbountPolicyInfoByPolicyAndHolding(out EdorseToEDM.EmailProviderWcfSvc.MailInfo[] mailObjects, string channelType, string policy, string policyHolding, bool includeAttachment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmailProvider/GetMailInfoByReference", ReplyAction="http://tempuri.org/IEmailProvider/GetMailInfoByReferenceResponse")]
        ITUtility.ProcessResult GetMailInfoByReference(out EdorseToEDM.EmailProviderWcfSvc.MailInfo[] mailObjects, string refName, string refValue, bool includeAttachment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmailProvider/GetMailInfoByAppNo", ReplyAction="http://tempuri.org/IEmailProvider/GetMailInfoByAppNoResponse")]
        ITUtility.ProcessResult GetMailInfoByAppNo(out EdorseToEDM.EmailProviderWcfSvc.MailInfo[] mailObjects, string appNo, bool includeAttachment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmailProvider/GetMailAboutPolicyInfo", ReplyAction="http://tempuri.org/IEmailProvider/GetMailAboutPolicyInfoResponse")]
        ITUtility.ProcessResult GetMailAboutPolicyInfo(out EdorseToEDM.EmailProviderWcfSvc.MailInfo[] mailObjects, long[] policyId, bool includeAttachment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmailProvider/GetMailAbountPolicyInfoByPolicyNo", ReplyAction="http://tempuri.org/IEmailProvider/GetMailAbountPolicyInfoByPolicyNoResponse")]
        ITUtility.ProcessResult GetMailAbountPolicyInfoByPolicyNo(out EdorseToEDM.EmailProviderWcfSvc.MailInfo[] mailObjects, string channelType, string policy, bool includeAttachment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmailProvider/GetFileAttechments", ReplyAction="http://tempuri.org/IEmailProvider/GetFileAttechmentsResponse")]
        ITUtility.ProcessResult GetFileAttechments(out EdorseToEDM.EmailProviderWcfSvc.File_Upload[] mailObjects, System.Nullable<long>[] mailIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmailProvider/GetMailHistoryByPolicyId", ReplyAction="http://tempuri.org/IEmailProvider/GetMailHistoryByPolicyIdResponse")]
        ITUtility.ProcessResult GetMailHistoryByPolicyId(out EdorseToEDM.EmailProviderWcfSvc.MailInfo[] mailObjects, long policyId, bool includeAttachment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmailProvider/GetMailHistoryByAppNo", ReplyAction="http://tempuri.org/IEmailProvider/GetMailHistoryByAppNoResponse")]
        ITUtility.ProcessResult GetMailHistoryByAppNo(out EdorseToEDM.EmailProviderWcfSvc.MailInfo[] mailObjects, string appNo, bool includeAttachment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmailProvider/SendMailAndOutMailId", ReplyAction="http://tempuri.org/IEmailProvider/SendMailAndOutMailIdResponse")]
        ITUtility.ProcessResult SendMailAndOutMailId(out long mailId, EdorseToEDM.EmailProviderWcfSvc.MailParams param, string userID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEmailProviderChannel : EdorseToEDM.EmailProviderWcfSvc.IEmailProvider, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmailProviderClient : System.ServiceModel.ClientBase<EdorseToEDM.EmailProviderWcfSvc.IEmailProvider>, EdorseToEDM.EmailProviderWcfSvc.IEmailProvider {
        
        public EmailProviderClient() {
        }
        
        public EmailProviderClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmailProviderClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmailProviderClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmailProviderClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ITUtility.ProcessResult SendMail(EdorseToEDM.EmailProviderWcfSvc.MailParams param, string userID) {
            return base.Channel.SendMail(param, userID);
        }
        
        public ITUtility.ProcessResult SendMailByAlternateView(out long mailId, EdorseToEDM.EmailProviderWcfSvc.MailParamsOld param, string userID) {
            return base.Channel.SendMailByAlternateView(out mailId, param, userID);
        }
        
        public ITUtility.ProcessResult SendMailOldVersion(EdorseToEDM.EmailProviderWcfSvc.MailParamsOld param, string userID) {
            return base.Channel.SendMailOldVersion(param, userID);
        }
        
        public ITUtility.ProcessResult GetMailAboutPolicyInfoByMailId(out EdorseToEDM.EmailProviderWcfSvc.MailInfo[] mailObjects, long[] mailId, bool includeAttachment) {
            return base.Channel.GetMailAboutPolicyInfoByMailId(out mailObjects, mailId, includeAttachment);
        }
        
        public ITUtility.ProcessResult GetMailAbountPolicyInfoByPolicyAndHolding(out EdorseToEDM.EmailProviderWcfSvc.MailInfo[] mailObjects, string channelType, string policy, string policyHolding, bool includeAttachment) {
            return base.Channel.GetMailAbountPolicyInfoByPolicyAndHolding(out mailObjects, channelType, policy, policyHolding, includeAttachment);
        }
        
        public ITUtility.ProcessResult GetMailInfoByReference(out EdorseToEDM.EmailProviderWcfSvc.MailInfo[] mailObjects, string refName, string refValue, bool includeAttachment) {
            return base.Channel.GetMailInfoByReference(out mailObjects, refName, refValue, includeAttachment);
        }
        
        public ITUtility.ProcessResult GetMailInfoByAppNo(out EdorseToEDM.EmailProviderWcfSvc.MailInfo[] mailObjects, string appNo, bool includeAttachment) {
            return base.Channel.GetMailInfoByAppNo(out mailObjects, appNo, includeAttachment);
        }
        
        public ITUtility.ProcessResult GetMailAboutPolicyInfo(out EdorseToEDM.EmailProviderWcfSvc.MailInfo[] mailObjects, long[] policyId, bool includeAttachment) {
            return base.Channel.GetMailAboutPolicyInfo(out mailObjects, policyId, includeAttachment);
        }
        
        public ITUtility.ProcessResult GetMailAbountPolicyInfoByPolicyNo(out EdorseToEDM.EmailProviderWcfSvc.MailInfo[] mailObjects, string channelType, string policy, bool includeAttachment) {
            return base.Channel.GetMailAbountPolicyInfoByPolicyNo(out mailObjects, channelType, policy, includeAttachment);
        }
        
        public ITUtility.ProcessResult GetFileAttechments(out EdorseToEDM.EmailProviderWcfSvc.File_Upload[] mailObjects, System.Nullable<long>[] mailIds) {
            return base.Channel.GetFileAttechments(out mailObjects, mailIds);
        }
        
        public ITUtility.ProcessResult GetMailHistoryByPolicyId(out EdorseToEDM.EmailProviderWcfSvc.MailInfo[] mailObjects, long policyId, bool includeAttachment) {
            return base.Channel.GetMailHistoryByPolicyId(out mailObjects, policyId, includeAttachment);
        }
        
        public ITUtility.ProcessResult GetMailHistoryByAppNo(out EdorseToEDM.EmailProviderWcfSvc.MailInfo[] mailObjects, string appNo, bool includeAttachment) {
            return base.Channel.GetMailHistoryByAppNo(out mailObjects, appNo, includeAttachment);
        }
        
        public ITUtility.ProcessResult SendMailAndOutMailId(out long mailId, EdorseToEDM.EmailProviderWcfSvc.MailParams param, string userID) {
            return base.Channel.SendMailAndOutMailId(out mailId, param, userID);
        }
    }
}
