//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdorseToEDM.BatchTransSvc {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataBatchTrans_Log", Namespace="http://schemas.datacontract.org/2004/07/BatTrans.DataContract")]
    [System.SerializableAttribute()]
    public partial class DataBatchTrans_Log : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BatchLog_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> Batch_DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Batch_Date_StrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColorRowField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CompletedCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EdorseToEDM.BatchTransSvc.DATA_DETAILS[] DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EditVerifyStsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorDetailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProgramNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> SeqField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StartCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TimeOverCountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BatchLog_Id {
            get {
                return this.BatchLog_IdField;
            }
            set {
                if ((object.ReferenceEquals(this.BatchLog_IdField, value) != true)) {
                    this.BatchLog_IdField = value;
                    this.RaisePropertyChanged("BatchLog_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Batch_Date {
            get {
                return this.Batch_DateField;
            }
            set {
                if ((this.Batch_DateField.Equals(value) != true)) {
                    this.Batch_DateField = value;
                    this.RaisePropertyChanged("Batch_Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Batch_Date_Str {
            get {
                return this.Batch_Date_StrField;
            }
            set {
                if ((object.ReferenceEquals(this.Batch_Date_StrField, value) != true)) {
                    this.Batch_Date_StrField = value;
                    this.RaisePropertyChanged("Batch_Date_Str");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ColorRow {
            get {
                return this.ColorRowField;
            }
            set {
                if ((object.ReferenceEquals(this.ColorRowField, value) != true)) {
                    this.ColorRowField = value;
                    this.RaisePropertyChanged("ColorRow");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CompletedCount {
            get {
                return this.CompletedCountField;
            }
            set {
                if ((this.CompletedCountField.Equals(value) != true)) {
                    this.CompletedCountField = value;
                    this.RaisePropertyChanged("CompletedCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EdorseToEDM.BatchTransSvc.DATA_DETAILS[] Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EditVerifySts {
            get {
                return this.EditVerifyStsField;
            }
            set {
                if ((object.ReferenceEquals(this.EditVerifyStsField, value) != true)) {
                    this.EditVerifyStsField = value;
                    this.RaisePropertyChanged("EditVerifySts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorCount {
            get {
                return this.ErrorCountField;
            }
            set {
                if ((this.ErrorCountField.Equals(value) != true)) {
                    this.ErrorCountField = value;
                    this.RaisePropertyChanged("ErrorCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorDetail {
            get {
                return this.ErrorDetailField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorDetailField, value) != true)) {
                    this.ErrorDetailField = value;
                    this.RaisePropertyChanged("ErrorDetail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProgramName {
            get {
                return this.ProgramNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProgramNameField, value) != true)) {
                    this.ProgramNameField = value;
                    this.RaisePropertyChanged("ProgramName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> Seq {
            get {
                return this.SeqField;
            }
            set {
                if ((this.SeqField.Equals(value) != true)) {
                    this.SeqField = value;
                    this.RaisePropertyChanged("Seq");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StartCount {
            get {
                return this.StartCountField;
            }
            set {
                if ((this.StartCountField.Equals(value) != true)) {
                    this.StartCountField = value;
                    this.RaisePropertyChanged("StartCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TimeOverCount {
            get {
                return this.TimeOverCountField;
            }
            set {
                if ((this.TimeOverCountField.Equals(value) != true)) {
                    this.TimeOverCountField = value;
                    this.RaisePropertyChanged("TimeOverCount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DATA_DETAILS", Namespace="http://schemas.datacontract.org/2004/07/BatTrans.DataContract")]
    [System.SerializableAttribute()]
    public partial class DATA_DETAILS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> BatchDetail_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompleteddateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Edit_VerifyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorDetailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrordateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OwnerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StartdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Status_DescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Status_VerifyDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TimeOverdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UpdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VerifyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VerifyByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VerifyDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> BatchDetail_Id {
            get {
                return this.BatchDetail_IdField;
            }
            set {
                if ((this.BatchDetail_IdField.Equals(value) != true)) {
                    this.BatchDetail_IdField = value;
                    this.RaisePropertyChanged("BatchDetail_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Completeddate {
            get {
                return this.CompleteddateField;
            }
            set {
                if ((object.ReferenceEquals(this.CompleteddateField, value) != true)) {
                    this.CompleteddateField = value;
                    this.RaisePropertyChanged("Completeddate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Edit_Verify {
            get {
                return this.Edit_VerifyField;
            }
            set {
                if ((object.ReferenceEquals(this.Edit_VerifyField, value) != true)) {
                    this.Edit_VerifyField = value;
                    this.RaisePropertyChanged("Edit_Verify");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorDetail {
            get {
                return this.ErrorDetailField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorDetailField, value) != true)) {
                    this.ErrorDetailField = value;
                    this.RaisePropertyChanged("ErrorDetail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Errordate {
            get {
                return this.ErrordateField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrordateField, value) != true)) {
                    this.ErrordateField = value;
                    this.RaisePropertyChanged("Errordate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Owner {
            get {
                return this.OwnerField;
            }
            set {
                if ((object.ReferenceEquals(this.OwnerField, value) != true)) {
                    this.OwnerField = value;
                    this.RaisePropertyChanged("Owner");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Startdate {
            get {
                return this.StartdateField;
            }
            set {
                if ((object.ReferenceEquals(this.StartdateField, value) != true)) {
                    this.StartdateField = value;
                    this.RaisePropertyChanged("Startdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status_Desc {
            get {
                return this.Status_DescField;
            }
            set {
                if ((object.ReferenceEquals(this.Status_DescField, value) != true)) {
                    this.Status_DescField = value;
                    this.RaisePropertyChanged("Status_Desc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status_VerifyDesc {
            get {
                return this.Status_VerifyDescField;
            }
            set {
                if ((object.ReferenceEquals(this.Status_VerifyDescField, value) != true)) {
                    this.Status_VerifyDescField = value;
                    this.RaisePropertyChanged("Status_VerifyDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelNo {
            get {
                return this.TelNoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelNoField, value) != true)) {
                    this.TelNoField = value;
                    this.RaisePropertyChanged("TelNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TimeOverdate {
            get {
                return this.TimeOverdateField;
            }
            set {
                if ((object.ReferenceEquals(this.TimeOverdateField, value) != true)) {
                    this.TimeOverdateField = value;
                    this.RaisePropertyChanged("TimeOverdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Update {
            get {
                return this.UpdateField;
            }
            set {
                if ((object.ReferenceEquals(this.UpdateField, value) != true)) {
                    this.UpdateField = value;
                    this.RaisePropertyChanged("Update");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Verify {
            get {
                return this.VerifyField;
            }
            set {
                if ((object.ReferenceEquals(this.VerifyField, value) != true)) {
                    this.VerifyField = value;
                    this.RaisePropertyChanged("Verify");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VerifyBy {
            get {
                return this.VerifyByField;
            }
            set {
                if ((object.ReferenceEquals(this.VerifyByField, value) != true)) {
                    this.VerifyByField = value;
                    this.RaisePropertyChanged("VerifyBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VerifyDate {
            get {
                return this.VerifyDateField;
            }
            set {
                if ((object.ReferenceEquals(this.VerifyDateField, value) != true)) {
                    this.VerifyDateField = value;
                    this.RaisePropertyChanged("VerifyDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VERIFY_INFO", Namespace="http://schemas.datacontract.org/2004/07/BatTrans.DataContract")]
    [System.SerializableAttribute()]
    public partial class VERIFY_INFO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EdorseToEDM.BatchTransSvc.VERIFY_DETAIL[] BatchDetailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VerifyBYField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EdorseToEDM.BatchTransSvc.VERIFY_DETAIL[] BatchDetail {
            get {
                return this.BatchDetailField;
            }
            set {
                if ((object.ReferenceEquals(this.BatchDetailField, value) != true)) {
                    this.BatchDetailField = value;
                    this.RaisePropertyChanged("BatchDetail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VerifyBY {
            get {
                return this.VerifyBYField;
            }
            set {
                if ((object.ReferenceEquals(this.VerifyBYField, value) != true)) {
                    this.VerifyBYField = value;
                    this.RaisePropertyChanged("VerifyBY");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VERIFY_DETAIL", Namespace="http://schemas.datacontract.org/2004/07/BatTrans.DataContract")]
    [System.SerializableAttribute()]
    public partial class VERIFY_DETAIL : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> Batch_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Batch_StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> Batch_Id {
            get {
                return this.Batch_IdField;
            }
            set {
                if ((this.Batch_IdField.Equals(value) != true)) {
                    this.Batch_IdField = value;
                    this.RaisePropertyChanged("Batch_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Batch_Status {
            get {
                return this.Batch_StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.Batch_StatusField, value) != true)) {
                    this.Batch_StatusField = value;
                    this.RaisePropertyChanged("Batch_Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ArBatch_Info", Namespace="http://schemas.datacontract.org/2004/07/BatTrans.DataContract")]
    [System.SerializableAttribute()]
    public partial class ArBatch_Info : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BATCH_DESCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BATCH_NAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CHECK_BYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CRITICALField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DAYSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EdorseToEDM.BatchTransSvc.AR_BATCH_DETAIL[] DetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ERR_NOTIFYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ERR_SOLUTIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FULLNAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FULLNAME_UPDATE_BYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MONTHSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OWNERField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PROGRAM_PATHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RELATED_BATCHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RELATED_SYSTEMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string REPEAT_EVERYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string REPEAT_UNTIL_DURATIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RESULTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RUN_AS_USERField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SERVERField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string START_TIMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string STATUSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UPDATE_BYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UPDATE_DATEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WORK_TYPEField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BATCH_DESC {
            get {
                return this.BATCH_DESCField;
            }
            set {
                if ((object.ReferenceEquals(this.BATCH_DESCField, value) != true)) {
                    this.BATCH_DESCField = value;
                    this.RaisePropertyChanged("BATCH_DESC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BATCH_NAME {
            get {
                return this.BATCH_NAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.BATCH_NAMEField, value) != true)) {
                    this.BATCH_NAMEField = value;
                    this.RaisePropertyChanged("BATCH_NAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CHECK_BY {
            get {
                return this.CHECK_BYField;
            }
            set {
                if ((object.ReferenceEquals(this.CHECK_BYField, value) != true)) {
                    this.CHECK_BYField = value;
                    this.RaisePropertyChanged("CHECK_BY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CRITICAL {
            get {
                return this.CRITICALField;
            }
            set {
                if ((object.ReferenceEquals(this.CRITICALField, value) != true)) {
                    this.CRITICALField = value;
                    this.RaisePropertyChanged("CRITICAL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DAYS {
            get {
                return this.DAYSField;
            }
            set {
                if ((object.ReferenceEquals(this.DAYSField, value) != true)) {
                    this.DAYSField = value;
                    this.RaisePropertyChanged("DAYS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EdorseToEDM.BatchTransSvc.AR_BATCH_DETAIL[] Details {
            get {
                return this.DetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailsField, value) != true)) {
                    this.DetailsField = value;
                    this.RaisePropertyChanged("Details");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ERR_NOTIFY {
            get {
                return this.ERR_NOTIFYField;
            }
            set {
                if ((object.ReferenceEquals(this.ERR_NOTIFYField, value) != true)) {
                    this.ERR_NOTIFYField = value;
                    this.RaisePropertyChanged("ERR_NOTIFY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ERR_SOLUTION {
            get {
                return this.ERR_SOLUTIONField;
            }
            set {
                if ((object.ReferenceEquals(this.ERR_SOLUTIONField, value) != true)) {
                    this.ERR_SOLUTIONField = value;
                    this.RaisePropertyChanged("ERR_SOLUTION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FULLNAME {
            get {
                return this.FULLNAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.FULLNAMEField, value) != true)) {
                    this.FULLNAMEField = value;
                    this.RaisePropertyChanged("FULLNAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FULLNAME_UPDATE_BY {
            get {
                return this.FULLNAME_UPDATE_BYField;
            }
            set {
                if ((object.ReferenceEquals(this.FULLNAME_UPDATE_BYField, value) != true)) {
                    this.FULLNAME_UPDATE_BYField = value;
                    this.RaisePropertyChanged("FULLNAME_UPDATE_BY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MONTHS {
            get {
                return this.MONTHSField;
            }
            set {
                if ((object.ReferenceEquals(this.MONTHSField, value) != true)) {
                    this.MONTHSField = value;
                    this.RaisePropertyChanged("MONTHS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OWNER {
            get {
                return this.OWNERField;
            }
            set {
                if ((object.ReferenceEquals(this.OWNERField, value) != true)) {
                    this.OWNERField = value;
                    this.RaisePropertyChanged("OWNER");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PROGRAM_PATH {
            get {
                return this.PROGRAM_PATHField;
            }
            set {
                if ((object.ReferenceEquals(this.PROGRAM_PATHField, value) != true)) {
                    this.PROGRAM_PATHField = value;
                    this.RaisePropertyChanged("PROGRAM_PATH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RELATED_BATCH {
            get {
                return this.RELATED_BATCHField;
            }
            set {
                if ((object.ReferenceEquals(this.RELATED_BATCHField, value) != true)) {
                    this.RELATED_BATCHField = value;
                    this.RaisePropertyChanged("RELATED_BATCH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RELATED_SYSTEM {
            get {
                return this.RELATED_SYSTEMField;
            }
            set {
                if ((object.ReferenceEquals(this.RELATED_SYSTEMField, value) != true)) {
                    this.RELATED_SYSTEMField = value;
                    this.RaisePropertyChanged("RELATED_SYSTEM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string REPEAT_EVERY {
            get {
                return this.REPEAT_EVERYField;
            }
            set {
                if ((object.ReferenceEquals(this.REPEAT_EVERYField, value) != true)) {
                    this.REPEAT_EVERYField = value;
                    this.RaisePropertyChanged("REPEAT_EVERY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string REPEAT_UNTIL_DURATION {
            get {
                return this.REPEAT_UNTIL_DURATIONField;
            }
            set {
                if ((object.ReferenceEquals(this.REPEAT_UNTIL_DURATIONField, value) != true)) {
                    this.REPEAT_UNTIL_DURATIONField = value;
                    this.RaisePropertyChanged("REPEAT_UNTIL_DURATION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RESULT {
            get {
                return this.RESULTField;
            }
            set {
                if ((object.ReferenceEquals(this.RESULTField, value) != true)) {
                    this.RESULTField = value;
                    this.RaisePropertyChanged("RESULT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RUN_AS_USER {
            get {
                return this.RUN_AS_USERField;
            }
            set {
                if ((object.ReferenceEquals(this.RUN_AS_USERField, value) != true)) {
                    this.RUN_AS_USERField = value;
                    this.RaisePropertyChanged("RUN_AS_USER");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SERVER {
            get {
                return this.SERVERField;
            }
            set {
                if ((object.ReferenceEquals(this.SERVERField, value) != true)) {
                    this.SERVERField = value;
                    this.RaisePropertyChanged("SERVER");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string START_TIME {
            get {
                return this.START_TIMEField;
            }
            set {
                if ((object.ReferenceEquals(this.START_TIMEField, value) != true)) {
                    this.START_TIMEField = value;
                    this.RaisePropertyChanged("START_TIME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string STATUS {
            get {
                return this.STATUSField;
            }
            set {
                if ((object.ReferenceEquals(this.STATUSField, value) != true)) {
                    this.STATUSField = value;
                    this.RaisePropertyChanged("STATUS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UPDATE_BY {
            get {
                return this.UPDATE_BYField;
            }
            set {
                if ((object.ReferenceEquals(this.UPDATE_BYField, value) != true)) {
                    this.UPDATE_BYField = value;
                    this.RaisePropertyChanged("UPDATE_BY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UPDATE_DATE {
            get {
                return this.UPDATE_DATEField;
            }
            set {
                if ((object.ReferenceEquals(this.UPDATE_DATEField, value) != true)) {
                    this.UPDATE_DATEField = value;
                    this.RaisePropertyChanged("UPDATE_DATE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WORK_TYPE {
            get {
                return this.WORK_TYPEField;
            }
            set {
                if ((object.ReferenceEquals(this.WORK_TYPEField, value) != true)) {
                    this.WORK_TYPEField = value;
                    this.RaisePropertyChanged("WORK_TYPE");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AR_BATCH_DETAIL", Namespace="http://schemas.datacontract.org/2004/07/BatTrans.DataContract")]
    [System.SerializableAttribute()]
    public partial class AR_BATCH_DETAIL : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BATCH_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DAYSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Edit_RowField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FULLNAME_UPDATE_BYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MONTHSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string REPEAT_EVERYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string REPEAT_UNTIL_DURATIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string START_TIMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UPDATE_BYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> UPDATE_DATEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UPDATE_DATE_STRField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BATCH_ID {
            get {
                return this.BATCH_IDField;
            }
            set {
                if ((object.ReferenceEquals(this.BATCH_IDField, value) != true)) {
                    this.BATCH_IDField = value;
                    this.RaisePropertyChanged("BATCH_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DAYS {
            get {
                return this.DAYSField;
            }
            set {
                if ((object.ReferenceEquals(this.DAYSField, value) != true)) {
                    this.DAYSField = value;
                    this.RaisePropertyChanged("DAYS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Edit_Row {
            get {
                return this.Edit_RowField;
            }
            set {
                if ((object.ReferenceEquals(this.Edit_RowField, value) != true)) {
                    this.Edit_RowField = value;
                    this.RaisePropertyChanged("Edit_Row");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FULLNAME_UPDATE_BY {
            get {
                return this.FULLNAME_UPDATE_BYField;
            }
            set {
                if ((object.ReferenceEquals(this.FULLNAME_UPDATE_BYField, value) != true)) {
                    this.FULLNAME_UPDATE_BYField = value;
                    this.RaisePropertyChanged("FULLNAME_UPDATE_BY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MONTHS {
            get {
                return this.MONTHSField;
            }
            set {
                if ((object.ReferenceEquals(this.MONTHSField, value) != true)) {
                    this.MONTHSField = value;
                    this.RaisePropertyChanged("MONTHS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string REPEAT_EVERY {
            get {
                return this.REPEAT_EVERYField;
            }
            set {
                if ((object.ReferenceEquals(this.REPEAT_EVERYField, value) != true)) {
                    this.REPEAT_EVERYField = value;
                    this.RaisePropertyChanged("REPEAT_EVERY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string REPEAT_UNTIL_DURATION {
            get {
                return this.REPEAT_UNTIL_DURATIONField;
            }
            set {
                if ((object.ReferenceEquals(this.REPEAT_UNTIL_DURATIONField, value) != true)) {
                    this.REPEAT_UNTIL_DURATIONField = value;
                    this.RaisePropertyChanged("REPEAT_UNTIL_DURATION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string START_TIME {
            get {
                return this.START_TIMEField;
            }
            set {
                if ((object.ReferenceEquals(this.START_TIMEField, value) != true)) {
                    this.START_TIMEField = value;
                    this.RaisePropertyChanged("START_TIME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UPDATE_BY {
            get {
                return this.UPDATE_BYField;
            }
            set {
                if ((object.ReferenceEquals(this.UPDATE_BYField, value) != true)) {
                    this.UPDATE_BYField = value;
                    this.RaisePropertyChanged("UPDATE_BY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> UPDATE_DATE {
            get {
                return this.UPDATE_DATEField;
            }
            set {
                if ((this.UPDATE_DATEField.Equals(value) != true)) {
                    this.UPDATE_DATEField = value;
                    this.RaisePropertyChanged("UPDATE_DATE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UPDATE_DATE_STR {
            get {
                return this.UPDATE_DATE_STRField;
            }
            set {
                if ((object.ReferenceEquals(this.UPDATE_DATE_STRField, value) != true)) {
                    this.UPDATE_DATE_STRField = value;
                    this.RaisePropertyChanged("UPDATE_DATE_STR");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EDIT_DATA_ARBATCH", Namespace="http://schemas.datacontract.org/2004/07/BatTrans.DataContract")]
    [System.SerializableAttribute()]
    public partial class EDIT_DATA_ARBATCH : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Input_BATCH_DESCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Input_BATCH_NAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Input_CHECK_BYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Input_CRITICALField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Input_DAYSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Input_ERR_NOTIFYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Input_ERR_SOLUTIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Input_MONTHSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Input_OWNERField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Input_PROGRAM_PATHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Input_RELATED_BATCHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Input_RELATED_SYSTEMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Input_REPEAT_EVERYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Input_REPEAT_UNTIL_DURATIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Input_RESULTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Input_RUN_AS_USERField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Input_SERVERField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Input_START_TIMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Input_STATUSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Input_UPDATE_BYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> Input_UPDATE_DATEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Input_WORK_TYPEField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Input_BATCH_DESC {
            get {
                return this.Input_BATCH_DESCField;
            }
            set {
                if ((object.ReferenceEquals(this.Input_BATCH_DESCField, value) != true)) {
                    this.Input_BATCH_DESCField = value;
                    this.RaisePropertyChanged("Input_BATCH_DESC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Input_BATCH_NAME {
            get {
                return this.Input_BATCH_NAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.Input_BATCH_NAMEField, value) != true)) {
                    this.Input_BATCH_NAMEField = value;
                    this.RaisePropertyChanged("Input_BATCH_NAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Input_CHECK_BY {
            get {
                return this.Input_CHECK_BYField;
            }
            set {
                if ((object.ReferenceEquals(this.Input_CHECK_BYField, value) != true)) {
                    this.Input_CHECK_BYField = value;
                    this.RaisePropertyChanged("Input_CHECK_BY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Input_CRITICAL {
            get {
                return this.Input_CRITICALField;
            }
            set {
                if ((object.ReferenceEquals(this.Input_CRITICALField, value) != true)) {
                    this.Input_CRITICALField = value;
                    this.RaisePropertyChanged("Input_CRITICAL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Input_DAYS {
            get {
                return this.Input_DAYSField;
            }
            set {
                if ((object.ReferenceEquals(this.Input_DAYSField, value) != true)) {
                    this.Input_DAYSField = value;
                    this.RaisePropertyChanged("Input_DAYS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Input_ERR_NOTIFY {
            get {
                return this.Input_ERR_NOTIFYField;
            }
            set {
                if ((object.ReferenceEquals(this.Input_ERR_NOTIFYField, value) != true)) {
                    this.Input_ERR_NOTIFYField = value;
                    this.RaisePropertyChanged("Input_ERR_NOTIFY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Input_ERR_SOLUTION {
            get {
                return this.Input_ERR_SOLUTIONField;
            }
            set {
                if ((object.ReferenceEquals(this.Input_ERR_SOLUTIONField, value) != true)) {
                    this.Input_ERR_SOLUTIONField = value;
                    this.RaisePropertyChanged("Input_ERR_SOLUTION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Input_MONTHS {
            get {
                return this.Input_MONTHSField;
            }
            set {
                if ((object.ReferenceEquals(this.Input_MONTHSField, value) != true)) {
                    this.Input_MONTHSField = value;
                    this.RaisePropertyChanged("Input_MONTHS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Input_OWNER {
            get {
                return this.Input_OWNERField;
            }
            set {
                if ((object.ReferenceEquals(this.Input_OWNERField, value) != true)) {
                    this.Input_OWNERField = value;
                    this.RaisePropertyChanged("Input_OWNER");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Input_PROGRAM_PATH {
            get {
                return this.Input_PROGRAM_PATHField;
            }
            set {
                if ((object.ReferenceEquals(this.Input_PROGRAM_PATHField, value) != true)) {
                    this.Input_PROGRAM_PATHField = value;
                    this.RaisePropertyChanged("Input_PROGRAM_PATH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Input_RELATED_BATCH {
            get {
                return this.Input_RELATED_BATCHField;
            }
            set {
                if ((object.ReferenceEquals(this.Input_RELATED_BATCHField, value) != true)) {
                    this.Input_RELATED_BATCHField = value;
                    this.RaisePropertyChanged("Input_RELATED_BATCH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Input_RELATED_SYSTEM {
            get {
                return this.Input_RELATED_SYSTEMField;
            }
            set {
                if ((object.ReferenceEquals(this.Input_RELATED_SYSTEMField, value) != true)) {
                    this.Input_RELATED_SYSTEMField = value;
                    this.RaisePropertyChanged("Input_RELATED_SYSTEM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Input_REPEAT_EVERY {
            get {
                return this.Input_REPEAT_EVERYField;
            }
            set {
                if ((object.ReferenceEquals(this.Input_REPEAT_EVERYField, value) != true)) {
                    this.Input_REPEAT_EVERYField = value;
                    this.RaisePropertyChanged("Input_REPEAT_EVERY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Input_REPEAT_UNTIL_DURATION {
            get {
                return this.Input_REPEAT_UNTIL_DURATIONField;
            }
            set {
                if ((object.ReferenceEquals(this.Input_REPEAT_UNTIL_DURATIONField, value) != true)) {
                    this.Input_REPEAT_UNTIL_DURATIONField = value;
                    this.RaisePropertyChanged("Input_REPEAT_UNTIL_DURATION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Input_RESULT {
            get {
                return this.Input_RESULTField;
            }
            set {
                if ((object.ReferenceEquals(this.Input_RESULTField, value) != true)) {
                    this.Input_RESULTField = value;
                    this.RaisePropertyChanged("Input_RESULT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Input_RUN_AS_USER {
            get {
                return this.Input_RUN_AS_USERField;
            }
            set {
                if ((object.ReferenceEquals(this.Input_RUN_AS_USERField, value) != true)) {
                    this.Input_RUN_AS_USERField = value;
                    this.RaisePropertyChanged("Input_RUN_AS_USER");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Input_SERVER {
            get {
                return this.Input_SERVERField;
            }
            set {
                if ((object.ReferenceEquals(this.Input_SERVERField, value) != true)) {
                    this.Input_SERVERField = value;
                    this.RaisePropertyChanged("Input_SERVER");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Input_START_TIME {
            get {
                return this.Input_START_TIMEField;
            }
            set {
                if ((object.ReferenceEquals(this.Input_START_TIMEField, value) != true)) {
                    this.Input_START_TIMEField = value;
                    this.RaisePropertyChanged("Input_START_TIME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Input_STATUS {
            get {
                return this.Input_STATUSField;
            }
            set {
                if ((object.ReferenceEquals(this.Input_STATUSField, value) != true)) {
                    this.Input_STATUSField = value;
                    this.RaisePropertyChanged("Input_STATUS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Input_UPDATE_BY {
            get {
                return this.Input_UPDATE_BYField;
            }
            set {
                if ((object.ReferenceEquals(this.Input_UPDATE_BYField, value) != true)) {
                    this.Input_UPDATE_BYField = value;
                    this.RaisePropertyChanged("Input_UPDATE_BY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Input_UPDATE_DATE {
            get {
                return this.Input_UPDATE_DATEField;
            }
            set {
                if ((this.Input_UPDATE_DATEField.Equals(value) != true)) {
                    this.Input_UPDATE_DATEField = value;
                    this.RaisePropertyChanged("Input_UPDATE_DATE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Input_WORK_TYPE {
            get {
                return this.Input_WORK_TYPEField;
            }
            set {
                if ((object.ReferenceEquals(this.Input_WORK_TYPEField, value) != true)) {
                    this.Input_WORK_TYPEField = value;
                    this.RaisePropertyChanged("Input_WORK_TYPE");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EDIT_DATA_DEATAIL_ARBATCH", Namespace="http://schemas.datacontract.org/2004/07/BatTrans.DataContract")]
    [System.SerializableAttribute()]
    public partial class EDIT_DATA_DEATAIL_ARBATCH : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BATCH_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Input_DAYSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Input_MONTHSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Input_REPEAT_EVERYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Input_REPEAT_UNTIL_DURATIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Input_START_TIMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Input_UPDATE_BYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> Input_UPDATE_DATEField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BATCH_ID {
            get {
                return this.BATCH_IDField;
            }
            set {
                if ((object.ReferenceEquals(this.BATCH_IDField, value) != true)) {
                    this.BATCH_IDField = value;
                    this.RaisePropertyChanged("BATCH_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Input_DAYS {
            get {
                return this.Input_DAYSField;
            }
            set {
                if ((object.ReferenceEquals(this.Input_DAYSField, value) != true)) {
                    this.Input_DAYSField = value;
                    this.RaisePropertyChanged("Input_DAYS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Input_MONTHS {
            get {
                return this.Input_MONTHSField;
            }
            set {
                if ((object.ReferenceEquals(this.Input_MONTHSField, value) != true)) {
                    this.Input_MONTHSField = value;
                    this.RaisePropertyChanged("Input_MONTHS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Input_REPEAT_EVERY {
            get {
                return this.Input_REPEAT_EVERYField;
            }
            set {
                if ((object.ReferenceEquals(this.Input_REPEAT_EVERYField, value) != true)) {
                    this.Input_REPEAT_EVERYField = value;
                    this.RaisePropertyChanged("Input_REPEAT_EVERY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Input_REPEAT_UNTIL_DURATION {
            get {
                return this.Input_REPEAT_UNTIL_DURATIONField;
            }
            set {
                if ((object.ReferenceEquals(this.Input_REPEAT_UNTIL_DURATIONField, value) != true)) {
                    this.Input_REPEAT_UNTIL_DURATIONField = value;
                    this.RaisePropertyChanged("Input_REPEAT_UNTIL_DURATION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Input_START_TIME {
            get {
                return this.Input_START_TIMEField;
            }
            set {
                if ((object.ReferenceEquals(this.Input_START_TIMEField, value) != true)) {
                    this.Input_START_TIMEField = value;
                    this.RaisePropertyChanged("Input_START_TIME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Input_UPDATE_BY {
            get {
                return this.Input_UPDATE_BYField;
            }
            set {
                if ((object.ReferenceEquals(this.Input_UPDATE_BYField, value) != true)) {
                    this.Input_UPDATE_BYField = value;
                    this.RaisePropertyChanged("Input_UPDATE_BY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Input_UPDATE_DATE {
            get {
                return this.Input_UPDATE_DATEField;
            }
            set {
                if ((this.Input_UPDATE_DATEField.Equals(value) != true)) {
                    this.Input_UPDATE_DATEField = value;
                    this.RaisePropertyChanged("Input_UPDATE_DATE");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Program", Namespace="http://schemas.datacontract.org/2004/07/AppSecurityProvider")]
    [System.SerializableAttribute()]
    public partial class Program : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ApplicationIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DisplayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ProgramGroupIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProgramTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StartCommandField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UpdateByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UpdateDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ApplicationID {
            get {
                return this.ApplicationIDField;
            }
            set {
                if ((this.ApplicationIDField.Equals(value) != true)) {
                    this.ApplicationIDField = value;
                    this.RaisePropertyChanged("ApplicationID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Display {
            get {
                return this.DisplayField;
            }
            set {
                if ((this.DisplayField.Equals(value) != true)) {
                    this.DisplayField = value;
                    this.RaisePropertyChanged("Display");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ProgramGroupID {
            get {
                return this.ProgramGroupIDField;
            }
            set {
                if ((this.ProgramGroupIDField.Equals(value) != true)) {
                    this.ProgramGroupIDField = value;
                    this.RaisePropertyChanged("ProgramGroupID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProgramType {
            get {
                return this.ProgramTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ProgramTypeField, value) != true)) {
                    this.ProgramTypeField = value;
                    this.RaisePropertyChanged("ProgramType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StartCommand {
            get {
                return this.StartCommandField;
            }
            set {
                if ((object.ReferenceEquals(this.StartCommandField, value) != true)) {
                    this.StartCommandField = value;
                    this.RaisePropertyChanged("StartCommand");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UpdateBy {
            get {
                return this.UpdateByField;
            }
            set {
                if ((object.ReferenceEquals(this.UpdateByField, value) != true)) {
                    this.UpdateByField = value;
                    this.RaisePropertyChanged("UpdateBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UpdateDate {
            get {
                return this.UpdateDateField;
            }
            set {
                if ((this.UpdateDateField.Equals(value) != true)) {
                    this.UpdateDateField = value;
                    this.RaisePropertyChanged("UpdateDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BatchTransSvc.IBatTrans")]
    public interface IBatTrans {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBatTrans/AddTrans", ReplyAction="http://tempuri.org/IBatTrans/AddTransResponse")]
        ITUtility.ProcessResult AddTrans(out long transId, string programName, string serverDetail, System.DateTime beginTime, System.DateTime expectEndTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBatTrans/AddTransByCode", ReplyAction="http://tempuri.org/IBatTrans/AddTransByCodeResponse")]
        ITUtility.ProcessResult AddTransByCode(out long transId, string code, System.DateTime expectEndTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBatTrans/UpdateTrans", ReplyAction="http://tempuri.org/IBatTrans/UpdateTransResponse")]
        ITUtility.ProcessResult UpdateTrans(long transId, System.DateTime expectEndTime, System.DateTime realEndTime, char status, string errorDetail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBatTrans/GetDataBatTrans_Log", ReplyAction="http://tempuri.org/IBatTrans/GetDataBatTrans_LogResponse")]
        ITUtility.ProcessResult GetDataBatTrans_Log(out EdorseToEDM.BatchTransSvc.DataBatchTrans_Log[] dataBatTans_Log, System.DateTime startDate, System.DateTime endDate, string typeselect);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBatTrans/EditVerify", ReplyAction="http://tempuri.org/IBatTrans/EditVerifyResponse")]
        ITUtility.ProcessResult EditVerify(EdorseToEDM.BatchTransSvc.VERIFY_INFO[] dataUpdate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBatTrans/GetDetail_ArBatch", ReplyAction="http://tempuri.org/IBatTrans/GetDetail_ArBatchResponse")]
        ITUtility.ProcessResult GetDetail_ArBatch(out EdorseToEDM.BatchTransSvc.ArBatch_Info[] dataArBatch_Info, System.Nullable<long> id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBatTrans/GetDetail_AR_BATCH_DETAIL", ReplyAction="http://tempuri.org/IBatTrans/GetDetail_AR_BATCH_DETAILResponse")]
        ITUtility.ProcessResult GetDetail_AR_BATCH_DETAIL(out EdorseToEDM.BatchTransSvc.AR_BATCH_DETAIL[] dataArBatchDetail, string arbatchID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBatTrans/SaveData_AR_BATCH", ReplyAction="http://tempuri.org/IBatTrans/SaveData_AR_BATCHResponse")]
        ITUtility.ProcessResult SaveData_AR_BATCH(EdorseToEDM.BatchTransSvc.EDIT_DATA_ARBATCH[] editDataArBatch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBatTrans/SaveData_AR_BATCH_DETAIL", ReplyAction="http://tempuri.org/IBatTrans/SaveData_AR_BATCH_DETAILResponse")]
        ITUtility.ProcessResult SaveData_AR_BATCH_DETAIL(EdorseToEDM.BatchTransSvc.EDIT_DATA_DEATAIL_ARBATCH[] editDataDetailArBatch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBatTrans/SaveDataARBATCH_AND_BATCHDETAIL", ReplyAction="http://tempuri.org/IBatTrans/SaveDataARBATCH_AND_BATCHDETAILResponse")]
        ITUtility.ProcessResult SaveDataARBATCH_AND_BATCHDETAIL(EdorseToEDM.BatchTransSvc.EDIT_DATA_ARBATCH[] dataARBATCH, EdorseToEDM.BatchTransSvc.EDIT_DATA_DEATAIL_ARBATCH[] dataARBATCH_DEATAL, string userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBatTrans/GetPermission", ReplyAction="http://tempuri.org/IBatTrans/GetPermissionResponse")]
        ITUtility.ProcessResult GetPermission(out EdorseToEDM.BatchTransSvc.Program[] dataObject, string USER_ID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBatTransChannel : EdorseToEDM.BatchTransSvc.IBatTrans, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BatTransClient : System.ServiceModel.ClientBase<EdorseToEDM.BatchTransSvc.IBatTrans>, EdorseToEDM.BatchTransSvc.IBatTrans {
        
        public BatTransClient() {
        }
        
        public BatTransClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BatTransClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BatTransClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BatTransClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ITUtility.ProcessResult AddTrans(out long transId, string programName, string serverDetail, System.DateTime beginTime, System.DateTime expectEndTime) {
            return base.Channel.AddTrans(out transId, programName, serverDetail, beginTime, expectEndTime);
        }
        
        public ITUtility.ProcessResult AddTransByCode(out long transId, string code, System.DateTime expectEndTime) {
            return base.Channel.AddTransByCode(out transId, code, expectEndTime);
        }
        
        public ITUtility.ProcessResult UpdateTrans(long transId, System.DateTime expectEndTime, System.DateTime realEndTime, char status, string errorDetail) {
            return base.Channel.UpdateTrans(transId, expectEndTime, realEndTime, status, errorDetail);
        }
        
        public ITUtility.ProcessResult GetDataBatTrans_Log(out EdorseToEDM.BatchTransSvc.DataBatchTrans_Log[] dataBatTans_Log, System.DateTime startDate, System.DateTime endDate, string typeselect) {
            return base.Channel.GetDataBatTrans_Log(out dataBatTans_Log, startDate, endDate, typeselect);
        }
        
        public ITUtility.ProcessResult EditVerify(EdorseToEDM.BatchTransSvc.VERIFY_INFO[] dataUpdate) {
            return base.Channel.EditVerify(dataUpdate);
        }
        
        public ITUtility.ProcessResult GetDetail_ArBatch(out EdorseToEDM.BatchTransSvc.ArBatch_Info[] dataArBatch_Info, System.Nullable<long> id) {
            return base.Channel.GetDetail_ArBatch(out dataArBatch_Info, id);
        }
        
        public ITUtility.ProcessResult GetDetail_AR_BATCH_DETAIL(out EdorseToEDM.BatchTransSvc.AR_BATCH_DETAIL[] dataArBatchDetail, string arbatchID) {
            return base.Channel.GetDetail_AR_BATCH_DETAIL(out dataArBatchDetail, arbatchID);
        }
        
        public ITUtility.ProcessResult SaveData_AR_BATCH(EdorseToEDM.BatchTransSvc.EDIT_DATA_ARBATCH[] editDataArBatch) {
            return base.Channel.SaveData_AR_BATCH(editDataArBatch);
        }
        
        public ITUtility.ProcessResult SaveData_AR_BATCH_DETAIL(EdorseToEDM.BatchTransSvc.EDIT_DATA_DEATAIL_ARBATCH[] editDataDetailArBatch) {
            return base.Channel.SaveData_AR_BATCH_DETAIL(editDataDetailArBatch);
        }
        
        public ITUtility.ProcessResult SaveDataARBATCH_AND_BATCHDETAIL(EdorseToEDM.BatchTransSvc.EDIT_DATA_ARBATCH[] dataARBATCH, EdorseToEDM.BatchTransSvc.EDIT_DATA_DEATAIL_ARBATCH[] dataARBATCH_DEATAL, string userID) {
            return base.Channel.SaveDataARBATCH_AND_BATCHDETAIL(dataARBATCH, dataARBATCH_DEATAL, userID);
        }
        
        public ITUtility.ProcessResult GetPermission(out EdorseToEDM.BatchTransSvc.Program[] dataObject, string USER_ID) {
            return base.Channel.GetPermission(out dataObject, USER_ID);
        }
    }
}
